### ISSUE TITLE
categories

### ISSUE THREAD

**Issue by AlexPAV** [lsielewicz/HomeBudgetViewer#8]
it's desirable to separate the categories of expenses and icomes (for samples: http://www.investingforme.com/ifm-budget-lines), and add the date of transaction.
Thanks.

**Comment by lsielewicz** [comment]
Thank you for your feedback, I think it should be implemented in next few days, as soon as I'll find some free time. 
Best regards

**Comment by lsielewicz** [comment]
Changes already merged to master branch.
